CREATE DATABASE sns_db;

USE sns_db;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255),
  email VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE users
ADD COLUMN profile_picture VARCHAR(255);

ALTER TABLE users
MODIFY COLUMN email VARCHAR(320);

ALTER TABLE posts
ADD COLUMN title VARCHAR(255);

ALTER TABLE posts
MODIFY COLUMN content LONGTEXT;