# Generated by Django 5.2.4 on 2025-09-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField()),
                ('music', models.CharField(max_length=100)),
                ('music_content', models.CharField()),
                ('image_link', models.URLField()),
                ('music_link', models.URLField()),
            ],
        ),
    ]
