# Generated by Django 5.2.4 on 2025-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('content', models.CharField()),
                ('music_content', models.CharField()),
                ('music', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
